# Name of the project
PROJECT_NAME = Minesweeper

# Output directory
BUILD = build

# All source code files
SRC = Minesweeper_main.c\
Src/Minesweeper_operations.c

TEST_OUTPUT = $(BUILD)/Test_$(PROJECT_NAME).out
